service: animal-crossing-api

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  memorySize: 256 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements
  - serverless-domain-manager

custom:	
  pythonRequirements:
    dockerizePip: true
    layer:
      name: animal-crossing-api-layer
      description: animal-crossing-api-layer description
      compatibleRuntimes:
        - python3.8
  customDomain:
    basePath: ''
    stage: ${self:provider.stage}
    domainName: api.churchofiron.co.uk
    certificateName: api.churchofiron.co.uk
    createRoute53Record: true
    endpointType: regional
    autoDomain: true

functions:
  app:
    package:
      patterns:
        - "main.py"
        - "!poetry.lock"
        - "!package.json"
        - "!package-lock.json"
        - "!.serverless/**"
        - "!.virtualenv/**"
        - "!node_modules/**"
        - "!MongoDBJsonImporter.py"

    handler: app.main.handler
    environment:
      STAGE: ${self:provider.stage}
      PROJECT_NAME: animal-crossing-api
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}